// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LocationPoint struct {
	ID         int64
	VehicleID  string
	TripID     string
	Latitude   float64
	Longitude  float64
	Bearing    pgtype.Float8
	Speed      pgtype.Float8
	Accuracy   pgtype.Float8
	Timestamp  int64
	ReceivedAt pgtype.Timestamptz
	DriverID   string
}

type User struct {
	ID           int64
	Name         string
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Vehicle struct {
	ID        string
	Label     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
