// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRecentLocations = `-- name: GetRecentLocations :many
SELECT DISTINCT ON (vehicle_id)
    vehicle_id, trip_id, latitude, longitude, bearing, speed, accuracy, timestamp, driver_id
FROM location_points
WHERE received_at > $1
ORDER BY vehicle_id, received_at DESC
`

type GetRecentLocationsRow struct {
	VehicleID string
	TripID    string
	Latitude  float64
	Longitude float64
	Bearing   pgtype.Float8
	Speed     pgtype.Float8
	Accuracy  pgtype.Float8
	Timestamp int64
	DriverID  string
}

func (q *Queries) GetRecentLocations(ctx context.Context, receivedAt pgtype.Timestamptz) ([]GetRecentLocationsRow, error) {
	rows, err := q.db.Query(ctx, getRecentLocations, receivedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentLocationsRow
	for rows.Next() {
		var i GetRecentLocationsRow
		if err := rows.Scan(
			&i.VehicleID,
			&i.TripID,
			&i.Latitude,
			&i.Longitude,
			&i.Bearing,
			&i.Speed,
			&i.Accuracy,
			&i.Timestamp,
			&i.DriverID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLocationPoint = `-- name: InsertLocationPoint :exec
INSERT INTO location_points (vehicle_id, trip_id, latitude, longitude, bearing, speed, accuracy, timestamp, driver_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertLocationPointParams struct {
	VehicleID string
	TripID    string
	Latitude  float64
	Longitude float64
	Bearing   pgtype.Float8
	Speed     pgtype.Float8
	Accuracy  pgtype.Float8
	Timestamp int64
	DriverID  string
}

func (q *Queries) InsertLocationPoint(ctx context.Context, arg InsertLocationPointParams) error {
	_, err := q.db.Exec(ctx, insertLocationPoint,
		arg.VehicleID,
		arg.TripID,
		arg.Latitude,
		arg.Longitude,
		arg.Bearing,
		arg.Speed,
		arg.Accuracy,
		arg.Timestamp,
		arg.DriverID,
	)
	return err
}

const upsertVehicle = `-- name: UpsertVehicle :exec
INSERT INTO vehicles (id)
VALUES ($1)
ON CONFLICT (id) DO UPDATE SET updated_at = NOW()
`

func (q *Queries) UpsertVehicle(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, upsertVehicle, id)
	return err
}
